'use client'

import Head from 'next/head'
import Faq from './(components)/Faq'
import Footer from './(components)/Footer'
import Revolutionize from './(components)/Revolutionize'

export default function Home() {
  return (
    <>
      <Head>
        <title>Scissors App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Faq />
        <Revolutionize />
        <Footer />
      </div>
    </>
  )
}
